FROM golang:1.25-alpine
WORKDIR /app

# Install git and build-base in case any dependencies need CGO or git
RUN apk add --no-cache git build-base
EXPOSE 8080

# We leave the CMD empty or as a default because the override will provide it
CMD ["go", "run", "."]